---
title: "Final Project"
output: pdf_document
fontsize: 12pt
---

```{r}
getwd() # make sure that the file is in the working directory

# load the data as a data.frame
birth <- read.csv(file = "chds_births.csv")

# produce the pair plots for different combinations of  variables in the dataset

par(mar = c(4, 4, 0, 0) + .1) # size of margins

P1 <- pairs(~ wt + gestation + parity  + mage + mwt, 
      labels = c("birth weight", "gestation", "parity",
                 "mage", "mwt"), 
      pch = 19,
      cex = 0.05,
      data = birth)

P2 <- pairs(~ wt + gestation + parity + meth + mht + mwt,
      labels = c("weight", "gestation", "parity", "meth", "mht", "mwt"),
      pch = 19,
      cex = 0.05,
      data = birth)
```

```{r}
# convert categorical variables to factors

# convert meth to non-numeric categorical variable
meth2 <- birth$meth

# "levels" of variable meth
methnames <- c("Caucasian","Mexican", "African-American","Asian", "Mixed", "Other")

# assign "Caucasian" level to values less than or equal to 5
# otherwise assign levels based on order in methnames vector
for(ii in 0:10) {
  if(ii<=5){
    meth2[meth2 == ii] <- "Caucasian"
  } else {
    meth2[meth2 == ii] <- methnames[ii-4]
  }
}

meth2 <- factor(meth2, levels = methnames) # order levels based on methnames
levels(meth2)
birth$meth <- meth2 # replace in dataset

############################################

# convert med to categorical variables
med2 <- birth$med

# "levels" of variable med
mednames <- c("elementary school", "middle school", "high school", "high school + trade", "high school + some college", "college grad", "trade school", "high school unclear")

med2 <- mednames[birth$med+1]

med2 <- factor(med2, levels = mednames) # order levels based on mednames
levels(med2)
birth$med <- med2 # replace in dataset

##########################################

# convert feth to categorical variables
feth2 <- birth$feth

# "levels" of variable feth
fethnames <- c("Caucasian","Mexican", "African-American","Asian", "Mixed", "Other")

# assign "Caucasian" level to values less than or equal to 5
# otherwise assign levels based on order in fethnames vector
for(ii in 0:10) {
  if(ii<=5){
    feth2[feth2 == ii] <- "Caucasian"
  } else {
    feth2[feth2 == ii] <- fethnames[ii-4]
  }
}

feth2 <- factor(feth2, levels = fethnames) # order levels based on methnames
levels(feth2)
birth$feth <- feth2 # replace in dataset

############################################

# convert fed to categorical variables
fed2 <- birth$fed

# "levels" of variable fed
fednames <- c("elementary school", "middle school", "high school", "high school + trade", "high school + some college", "college grad", "trade school", "high school unclear")

fed2 <- fednames[birth$fed+1]

fed2 <- factor(fed2, levels = fednames) # order levels based on fednames
levels(fed2)
birth$fed <- fed2 # replace in dataset

######################################################################

# marital
marital <- birth$marital
maritalnames <- c("married", "legally separated", "divorced", "widowed",
                  "never married") # new values
# encode the factor
marital2 <- rep(NA, length(marital))
for (ii in 1:5) {
  marital2[marital == ii] <- maritalnames[ii]
}
marital2 <- factor(marital2, levels = maritalnames)
birth$marital <- marital2
######################################################################
# income
income <- birth$income
incomenames <- c("under 2500", "2500-4999", "5000-7499", "7500-9999",
                  "10000-12499", "12500-14999", "15000-17499",
                 "17500-19999", "20000-22499", "over 22500") # new values
# encode the factor
income2 <- incomenames[income+1]
income2 <- factor(income2, levels = incomenames)
birth$income <- income2
############################################################
# smoke
smoke <- birth$smoke
smokenames <- c("never", "smokes now", "until pregnancy", 
                "used to, not anymore") # new values
# encode the factor
smoke2 <- smokenames[smoke+1]
smoke2 <- factor(smoke2, levels = smokenames)
birth$smoke <- smoke2
############################################################
# time
time <- birth$time
timenames <- c("never smoked", "still smokes", "during pregnancy", 
                "less than a year", "1-2 years", "2-3 years", "3-4 years",
               "5-9 years", "more than 10 years", 
               "quit but don't know when") # new values
# encode the factor
time2 <- timenames[time+1]
time2 <- factor(time2, levels = timenames)
birth$time <- time2
#############################################################
# number
number <- birth$number
numbernames <- c("never smoked", "1-4", "5-9", "10-14", "15-19", "20-29", "30-39",
                 "40-60", "more than 60", 
                 "smoked but don't know how much") # new values
# encode the factor
number2 <- numbernames[number+1]
number2 <- factor(number2, levels = numbernames)
birth$number <- number2

```

```{r}
# check how many observations contain too many NA's
n <- length(birth$wt) # number of total observations
boundary <- .10 * n # boundary to decide if there are too many NA's

NA.list <- NA # initialize the list of required covariates

# identify and display all required covariates
for (ii in 1:length(birth)) {
 if(sum(is.na(birth[ii])) >= boundary)
 {NA.list <- c(NA.list, colnames(birth)[ii])}
}
NA.list <- NA.list[2:length(NA.list)]
NA.list
```




## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```


